# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/vivado/NTT/NTT.runs/synth_1/NTT_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/vivado/NTT/NTT.cache/wt [current_project]
set_property parent.project_path C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/vivado/NTT/NTT.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/vivado/NTT/NTT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {POLY_LEN=64 N_INV_M=128} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ram_rom/bram_dp_word.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ntt/butterfly_unit.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ram_rom/exceed_W_addr_dec.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ram_rom/exceed_addr_dec.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ntt/mont_inv_transform.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ntt/ntt_butterfly.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ram_rom/rom_wNTT.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ram_rom/rom_w_inv_NTT.sv
  C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/rtl/ntt/ntt_top.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/vivado/NTT/NTT.srcs/constrs_1/new/conxdc.xdc
set_property used_in_implementation false [get_files C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/vivado/NTT/NTT.srcs/constrs_1/new/conxdc.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/FPGA/PQC-Hardware/FPGA-Based-NTT-Accelerator-for-PQC/vivado/NTT/NTT.srcs/utils_1/imports/synth_1/NTT_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top NTT_top -part xc7z010clg400-1 -flatten_hierarchy none
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NTT_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file NTT_top_utilization_synth.rpt -pb NTT_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
